### ISSUE TITLE
Задачи на списки

### ISSUE THREAD

**Issue by sov-87** [budkovmm/cslessons#4]
1. Реализовать динамический массив с использованием односвязного списка. Должны быть методы вставки элемента на заданное место и вырезки элемента по заданному индексу.
2. Сделать предыдущее задание с использованием двусвязного списка.
3. Написать программу, которая моделирует вставку и удаление элементов. В самом начале программы создать массив из 100 000 элементов. Удаление и добавление производить случайным образом в доступном диапазоне индексов. Моделировать 100 000 операций. Сравнить скорость работы программы для двух разных реализаций.

**Comment by budkovmm** [comment]
PR смержен https://github.com/budkovmm/cslessons/pull/6
